authors:
  Xiaokang2022:
    name: Xiaokang2022 # Author name
    description: > # Author description
      兴趣就是最好老师，<br>
      热爱才能做得更好！
    avatar: https://github.com/Xiaokang2022.png # Author avatar
    url: https://github.com/Xiaokang2022 # Author website URL

  I-love-study:
    name: I-love-study
    description: 请大声喊出我的名字吧~
    avatar: https://github.com/I-love-study.png
    url: https://github.com/I-love-study
