"""Support for color"""

import tkinter
import typing


def _get_control_lst(
    controller: tuple[typing.Callable[[float], float], float, float],
    length: int,
) -> list[float]:
    """Get a list of floating-point numbers generated by a control function"""
    delta = controller[2] - controller[1]
    lst = [controller[0](controller[1] + i/length*delta)
           for i in range(1, length+1)]
    if (maximum := max(lst)) == 0:
        return [controller[0](controller[1])] * length
    return [value/maximum for value in lst]


@typing.overload
def color(
    __color: tuple[str, str],
    /,
    proportion: float = 1,
    *,
    seqlength: int = 1,
    num: typing.Literal[1, 2, 3, 4] = 2,
    controller: tuple[typing.Callable[[float], float],
                      float, float] | None = None,
) -> str | list[str]: ...


@typing.overload
def color(
    __color: str,
    /,
    proportion: float = 1,
    *,
    seqlength: int = 1,
    num: typing.Literal[1, 2, 3, 4] = 2,
    controller: tuple[typing.Callable[[float], float],
                      float, float] | None = None,
) -> str | list[str]: ...


def color(
    __color: str | tuple[str, str],
    /,
    proportion: float = 1,
    *,
    seqlength: int = 1,
    num: typing.Literal[1, 2, 3, 4] = 2,
    controller: tuple[typing.Callable[[float], float],
                      float, float] | None = None,
) -> str | list[str]:
    """按一定比例给出已有 RGB 颜色字符串的渐变 RGB 颜色字符串，或者给出已有 RGB 颜色字符串的对比色

    * `color`: 颜色元组或列表 (初始颜色, 目标颜色)，或者一个颜色字符串（此时返回其对比色）
    * `proportion`: 改变比例（浮点数，范围为 0 ~ 1），默认值为 1
    * `seqlength`: 如果值为 1，则直接返回结果，其余情况返回长度为 `seqlength` 的渐变颜色列表，默认为 1
    * `num`: 每一通道的 16 进制位数，默认为 2 位，可选值为 1 ~ 4
    * `controller`: 比例值变化的控制器，为元组 (控制函数, 初始值, 终止值)，仅当参数 `seqlength` 大于 1 时生效，默认为等差变化
    """
    proportion = 0 if proportion < 0 else 1 if proportion > 1 else proportion

    key = 16 - (num << 2)
    format_ = f"#%0{num}X%0{num}X%0{num}X"

    if tkinter._default_root is None:
        tkinter.Tk().withdraw()

    if isinstance(__color, str):
        start = [c >> key for c in tkinter._default_root.winfo_rgb(__color)]
        end = [(1 << (num << 2)) - c - 1 for c in start]
    else:
        start = [c >> key for c in tkinter._default_root.winfo_rgb(__color[0])]
        end = [c >> key for c in tkinter._default_root.winfo_rgb(__color[1])]

    end = [s + round((e - s) * proportion) for s, e in zip(start, end)]

    if controller is None:
        controller = (lambda _: _), 0, 1

    proportion_lst = _get_control_lst(controller, seqlength)

    lst = [(format_ % tuple(c1 + round((c2-c1) * p)
            for c1, c2 in zip(start, end))) for p in proportion_lst]

    return lst[0] if seqlength == 1 else lst


def str_to_hex(__color: str, /, *, reverse: bool = False, add: int = 0) -> int:
    """Convert color strings to hexadecimal integers"""
    RGB = tkinter._get_temp_root().winfo_rgb(__color)
    tup = tuple(value >> 8 for value in RGB)
    for i in reversed(tup) if reverse else tup:
        add <<= 8
        add += i
    return add


def rgb_to_hex(r: int, g: int, b: int) -> int:
    """Convert r, g, b to RGB"""
    r <<= 8
    r += g
    r <<= 8
    r += b
    return r
